### ISSUE TITLE
User selects the month that the visualization software should centre the graph in

### ISSUE THREAD

**Issue by ArthurLai93** [jes97210/monthly-lollipops#7] opened 2021-01-01 03:15 UTC
User selects the month that the visualization software should centre the graph in.

**Comment by jes97210** [comment] 2021-01-02 01:12
As worded, this doesn't describe a task that we can code. Is this just a user story?

**Comment by jes97210** [comment] 2021-01-25 05:15
Will close as a duplicate of #10.

**Closed as completed by jes97210** 2021-01-25 05:15 UTC
Labels: enhancement
